corner-radius = 0;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

shadow = true;
shadow-radius = 20;
shadow-opacity = 0.6;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-color = "#000000";

fading = false;

inactive-opacity = 0.90;
active-opacity = 0.95;
frame-opacity = 1.0;
inactive-dim = 0.0;

active-border-color = "#7b2cbf";
border-width = 2;

backend = "glx";
vsync = true;
mark-wmwin-focused = true;
mark-ovlp-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = true;

wintypes:
{
  tooltip = { fade = false; shadow = true; opacity = 1.0; focus = true; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1.0; }
  dropdown_menu = { opacity = 1.0; }
};
